#!/usr/bin/env bash

set -eou pipefail
#set -x

docker stop -t1 telemetry-plugin

echo "+++ :bar_chart: Telemetry:"
cat "$BUILDKITE_TELEMETRY_PLUGIN_OUTFILE"

rm -rf -- "$BUILDKITE_TELEMETRY_PLUGIN_TMPDIR"
