#!/usr/bin/env bash

set -eou pipefail
#set -x

# TODO: proper tempdir scoped to this invocation

docker stop -t1 dstat
echo "+++ :bar_chart: Telemetry:"
cat "$BUILDKITE_TELEMETRY_PLUGIN_OUTFILE"

rm -rf -- "$BUILDKITE_TELEMETRY_PLUGIN_TMPDIR"
