#!/usr/bin/env bash

set -eou pipefail
#set -x

docker stop -t1 "$BUILDKITE_TELEMETRY_PLUGIN_CONTAINER_NAME" || true

vcpus=$(lscpu | awk -F ":" '/Thread/ { t=$2; }; /Core/ { c=$2; }; /Socket/ { s=$2; }; END { print s*c*t }')
phys_cpus=$(lscpu | awk -F ":" '/Core/ { c=$2; }; /Socket/ { s=$2; }; END { print s*c }')
ram_gb=$(awk '/MemTotal/ {printf "%d", $2/1024/1024}' /proc/meminfo)

echo "--- :bar_chart: Telemetry report below (node: ${vcpus} vCPUS (${phys_cpus} physical CPUs), ${ram_gb} GB):"

cat "$BUILDKITE_TELEMETRY_PLUGIN_OUTFILE"

rm -rf -- "$BUILDKITE_TELEMETRY_PLUGIN_TMPDIR"
