#!/usr/bin/env bash

set -eou pipefail
set -x

# TODO: proper tempdir scoped to this invocation

docker run \
  --rm \
  --init \
  --detach \
  --name dstat \
  --pid host \
  --net host \
  --userns host \
  -v "$BUILDKITE_TELEMETRY_PLUGIN_TMPDIR:$BUILDKITE_TELEMETRY_PLUGIN_TMPDIR" \
  ghcr.io/planetscale/telemetry-buildkite-plugin:latest \
  "dstat -t -c -m -n --disk-tps --disk --color --noupdate 10 > $BUILDKITE_TELEMETRY_PLUGIN_OUTFILE"

docker ps -a
