#!/usr/bin/env bash

set -eou pipefail
#set -x

TAG="v0.0.6"

docker run \
  --rm \
  --init \
  --detach \
  --name "$BUILDKITE_TELEMETRY_PLUGIN_CONTAINER_NAME" \
  --pid host \
  --net host \
  --userns host \
  -v "$BUILDKITE_TELEMETRY_PLUGIN_TMPDIR:$BUILDKITE_TELEMETRY_PLUGIN_TMPDIR" \
  ghcr.io/planetscale/telemetry-buildkite-plugin:"$TAG" \
  "dstat -t -c -m -n --disk-tps --disk --color --noupdate 10 > $BUILDKITE_TELEMETRY_PLUGIN_OUTFILE"

docker ps -a
